# Generated by Django 4.2.5 on 2023-10-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_portfolio_alter_student_major_student_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
